[package]
name = "crowdsec_filter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.2.3"
serde = { version = "1", features = ["derive"] }
flexbuffers = "*"
uuid = {version = "1.17.0", features = ["v4"]}
log = "0.4"


[profile.release]
lto = true
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "debuginfo"